[package]
name = "ultragraph"
version = "0.5.5"
edition = "2021"
rust-version = "1.80"
repository = "https://github.com/deepcausality/deep_causality.rs"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]
license = "MIT"
description = "Hypergraph data structure."
documentation = "https://docs.rs/ultragraph"
homepage = "https://github.com/deepcausality/deep_causality/tree/main/ultragraph"
categories = ["data-structures"]
keywords = ["data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies.deep_causality_macros]
path = "../deep_causality_macros"
version = "^0.4"


[dependencies]
ahash = "0.8"
petgraph = "0.7"


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = { version = "0.9", features = ["small_rng"] }


[[bench]]
name = "bench_main"
harness = false
