[package]
name = "ultragraph"
version = "0.8.2"
edition = "2021"
rust-version = "1.80"
repository = "https://github.com/deepcausality/deep_causality.rs"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]
license = "MIT"
description = "Hypergraph data structure."
documentation = "https://docs.rs/ultragraph"
homepage = "https://github.com/deepcausality/deep_causality/tree/main/ultragraph"
categories = ["data-structures"]
keywords = ["data-structures"]
exclude = ["*.bazel", "*/*.bazel",  "*.bazel.*", "BUILD", "BUILD.bazel", "MODULE.bazel", ".bazelignore",".bazelrc", "tests/**/*"]


[dependencies.deep_causality_macros]
path = "../deep_causality_macros"
version = "0.8.0"


[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }
rand = { version = "0.9", features = ["small_rng"] }


[[bench]]
name = "bench_main"
harness = false
