# SPDX-License-Identifier: MIT
# Copyright (c) "2025" . The DeepCausality Authors and Contributors. All Rights Reserved.

[package]
name = "ultragraph"
version = "0.8.13"
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

repository = "https://github.com/deepcausality/deep_causality.rs"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]
description = "Hypergraph data structure."
documentation = "https://docs.rs/ultragraph"
homepage = "https://github.com/deepcausality/deep_causality/tree/main/ultragraph"
categories = ["data-structures"]
keywords = ["data-structures"]
exclude = ["*.bazel", "*/*.bazel", "*.bazel.*", "BUILD", "BUILD.bazel", "MODULE.bazel", ".bazelignore", ".bazelrc", "tests/**/*"]


[dev-dependencies]
criterion = {  version = "0.8.2" }
deep_causality_rand = { path = "../deep_causality_rand" }


[[bench]]
name = "bench_main"
harness = false

[[example]]
name = "ultragraph_example"
path = "examples/ultraph_example.rs"
