[package]
name = "physics_examples"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "no_lib.rs"


[dependencies]
deep_causality = { path = "../../deep_causality" }
deep_causality_core = { path = "../../deep_causality_core" }
deep_causality_physics = { path = "../../deep_causality_physics" }
deep_causality_multivector = { path = "../../deep_causality_multivector" }
deep_causality_tensor = { path = "../../deep_causality_tensor" }
deep_causality_topology = { path = "../../deep_causality_topology" }
deep_causality_num = { path = "../../deep_causality_num" }
deep_causality_sparse = { path = "../../deep_causality_sparse" }


[[example]]
name = "maxwell_example"
path = "maxwell_example/main.rs"

[[example]]
name = "grmhd_example"
path = "grmhd_example/main.rs"

[[example]]
name = "geometric_tilt_example"
path = "geometric_tilt_example/main.rs"

[[example]]
name = "algebraic_scanner"
path = "algebraic_scanner/main.rs"

[[example]]
name = "multi_physics_pipeline"
path = "multi_physics_pipeline/main.rs"

[[example]]
name = "quantum_counterfactual"
path = "quantum_counterfactual/main.rs"

[[example]]
name = "ikkt_matrix_model"
path = "ikkt_matrix_model/main.rs"

[[example]]
name = "gravitational_wave"
path = "gravitational_wave/main.rs"
