[package]
name = "physics_examples"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false


[lib]
path = "no_lib.rs"


[dependencies]
deep_causality = { path = "../../deep_causality" }
deep_causality_core = { path = "../../deep_causality_core" }
deep_causality_physics = { path = "../../deep_causality_physics", features = [
    "os-random",
] }
deep_causality_multivector = { path = "../../deep_causality_multivector" }
deep_causality_tensor = { path = "../../deep_causality_tensor" }
deep_causality_topology = { path = "../../deep_causality_topology" }
deep_causality_num = { path = "../../deep_causality_num" }
deep_causality_sparse = { path = "../../deep_causality_sparse" }
deep_causality_rand = { path = "../../deep_causality_rand", features = [
    "os-random",
] }


[[example]]
name = "algebraic_scanner"
path = "algebraic_scanner/main.rs"

[[example]]
name = "bernoulli_flow_network"
path = "bernoulli_flow_network/main.rs"

[[example]]
name = "carnot_cycle_engine"
path = "carnot_cycle_engine/main.rs"

[[example]]
name = "event_horizon_probe"
path = "event_horizon_probe/main.rs"

[[example]]
name = "geometric_tilt_example"
path = "geometric_tilt_example/main.rs"

[[example]]
name = "gravitational_wave"
path = "gravitational_wave/main.rs"

[[example]]
name = "grmhd_example"
path = "grmhd_example/main.rs"

[[example]]
name = "ikkt_matrix_model"
path = "ikkt_matrix_model/main.rs"

[[example]]
name = "laser_resonator_stability"
path = "laser_resonator_stability/main.rs"

[[example]]
name = "maxwell_example"
path = "maxwell_example/main.rs"

[[example]]
name = "multi_physics_pipeline"
path = "multi_physics_pipeline/main.rs"

[[example]]
name = "quantum_counterfactual"
path = "quantum_counterfactual/main.rs"

[[example]]
name = "quantum_geometric_tensor"
path = "quantum_geometric_tensor/main.rs"
