[package]
name = "example-csm"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
publish = false

[dependencies]
# For testing with latest commit in main repository
#deep_causality = { git = "https://github.com/deepcausality-rs/deep_causality", branch = "main" }
deep_causality = "0.7.0"
