[package]
name = "example-tokio"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
publish = false

[dependencies]
deep_causality = { path = "../../deep_causality" }
tokio = {version = "1.47", features = ["full"]}
