[package]
name = "example-starter"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For testing with latest commit in main
#deep_causality = { git = "https://github.com/deepcausality-rs/deep_causality", branch = "main" }
deep_causality = "0.7.0"
