[package]
name = "deep_causality_algorithms"
version = "0.2.10"
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
readme = "README.md"

description = "Computational causality algorithms and utils used in the DeepCausality project."
documentation = "https://docs.rs/deep_causality"
homepage = "https://deepcausality.com/"
repository = "https://github.com/deepcausality/deep_causality.rs"
keywords = ["surd", "causal-graph", "causal-reasoning", "algorithms"]
categories = ["algorithms", "science", "aerospace", "finance", "mathematics"]
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]
exclude = ["*.bazel", "*/*.bazel",  "*.bazel.*", "BUILD", "BUILD.bazel", "MODULE.bazel", ".bazelignore",".bazelrc", "tests/**/*"]


[[example]]
name = "example_mrmr"
path = "examples/example_mrmr.rs"


[[example]]
name = "example_mrmr_cdl"
path = "examples/example_mrmr_cdl.rs"


[[example]]
name = "example_surd"
path = "examples/example_surd.rs"


[dependencies.deep_causality_tensor]
path = "../deep_causality_tensor"
version = "0.4.0"


[dependencies.deep_causality_num]
path = "../deep_causality_num"
version = "0.2.0"

[dependencies.rayon]
version = "1.11"
optional = true


[features]
default = []
# Enables parallel execution of the SURD algorithm by adding a dependency on Rayon.
# Disabled by default.
parallel = ["dep:rayon"]


[package.metadata.docs.rs]
all-features = true

[dev-dependencies]
criterion = {  version = "0.8.2" }

[[bench]]
name = "mrmr_benchmark"
harness = false
