[package]
name = "medicine_examples"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false


[lib]
path = "no_lib.rs"


[dependencies]
deep_causality_core = { path = "../../deep_causality_core" }
deep_causality_physics = { path = "../../deep_causality_physics" }
deep_causality_tensor = { path = "../../deep_causality_tensor" }
deep_causality_topology = { path = "../../deep_causality_topology" }
deep_causality_num = { path = "../../deep_causality_num" }

[[example]]
name = "aneurysm_risk"
path = "aneurysm_risk/main.rs"

[[example]]
name = "diving_decompression"
path = "diving_decompression/main.rs"

[[example]]
name = "epilepsy"
path = "epilepsy/main.rs"

[[example]]
name = "protein_folding"
path = "protein_folding/main.rs"

[[example]]
name = "tissue_classification"
path = "tissue_classification/main.rs"

[[example]]
name = "tumor_treatment"
path = "tumor_treatment/main.rs"
