[package]
name = "deep_causality_macros"
version = "0.4.5"
edition = "2021"
rust-version = "1.65"
repository = "https://github.com/deepcausality/deep_causality.rs"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]
license = "MIT"
description = "Procedural macros dependency for deep_causality; no standalone usage intended."
documentation = "https://docs.rs/deep_causality"

[lib]
proc-macro = true

[features]


[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[package.metadata.docs.rs]
all-features = true
