name: Rust SBOM

on:
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-and-attest:
    name: SBOM for ${{ matrix.crate }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        crate:
          - deep_causality
          - deep_causality_algorithms
          - deep_causality_ast
          - deep_causality_data_structures
          - deep_causality_discovery
          - deep_causality_haft
          - deep_causality_macros
          - deep_causality_multivector
          - deep_causality_num
          - deep_causality_rand
          - deep_causality_tensor
          - deep_causality_uncertain
          - ultragraph

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cargo-sbom
        run: cargo install cargo-sbom

      - name: Generate SBOM
        run: cargo sbom --cargo-package ${{ matrix.crate }} --output-format=spdx_json_2_3 > ${{ matrix.crate }}/${{ matrix.crate }}_sbom.spdx.json

      - name: Attest SBOM
        uses: actions/attest@v1
        with:
          subject-path: ./${{ matrix.crate }}
          predicate-type: spdxjson
          predicate-path: '${{ matrix.crate }}/${{ matrix.crate }}_sbom.spdx.json'

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.crate }}-sbom
          path: '${{ matrix.crate }}/${{ matrix.crate }}_sbom.spdx.json'