name: Rust SBOM

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-and-attest:
    name: SBOM for ${{ matrix.crate }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        crate:
          - deep_causality
          - deep_causality_algorithms
          - deep_causality_ast
          - deep_causality_data_structures
          - deep_causality_discovery
          - deep_causality_haft
          - deep_causality_macros
          - deep_causality_multivector
          - deep_causality_num
          - deep_causality_rand
          - deep_causality_tensor
          - deep_causality_uncertain
          - ultragraph

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-sbom
        run: cargo install cargo-sbom

      - name: Generate SBOM
        run: |
          set -euo pipefail
          cargo sbom --cargo-package "${{ matrix.crate }}" --output-format=spdx_json_2_3 > "${{ matrix.crate }}-sbom.spdx.json"

#     Attestion currently fails with Error: missing "id-token" permission. Please add "permissions: id-token: write" to your workflow.
#     Despite having "id-token" permission set.
#      - name: Attest
#        uses: actions/attest-sbom@v3
#        with:
#          subject-path: "${{ matrix.crate }}"
#          sbom-path: '${{ matrix.crate }}-sbom.spdx.json'

      - name: Upload SBOM to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.crate }}-sbom.spdx.json